library(testthat)
source("scripts/config.R")
source("scripts/sources.R")
source("scripts/coverage.R")
source("scripts/export.R")
source("scripts/update.R")
test_dir("tests/testthat", stop_on_failure = TRUE)
